[build-system]
requires = ["flit_core >=3.2,<4", "basemap", "nbsphinx"]
build-backend = "flit_core.buildapi"

[project]
name = "HMSFirepy"
authors = [{name = "Joel", email = "joel.chacon@cimat.mx"}]
dynamic = ["version", "description"]
